name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Generate pacman graph
        uses: maurodesouza/pacman-contribution-graph@main

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate Pacman contribution graph"
